site_name: Cloud Scripting
site_url: https://docs.cloudscripting.com/
copyright: Copyright &copy; Jelastic, Inc.

#use_absolute_urls: true
#:include_search true
#theme_center_lead: false


theme_dir: './theme/readthedocs'
repo_url: 'https://github.com/cloudscripting/docs/edit/1.8.2/docs/'

markdown_extensions:
  - admonition
  - toc
  - tables
  - markdown-tabs
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

pages:

- GETTING STARTED:
   - Overview: index.md
   - Quick Start: quick-start.md

- Creating Manifest:
   - Basic Configs: creating-manifest/basic-configs.md
   - Specifying Target Container: creating-manifest/selecting-containers.md
   - Actions: creating-manifest/actions.md
   - Events: creating-manifest/events.md
   - Placeholders: creating-manifest/placeholders.md
   - Conditions and Iterations: creating-manifest/conditions-and-iterations.md
   - Custom Scripts: creating-manifest/custom-scripts.md
   - Mixins: creating-manifest/mixins.md
   - Add-Ons: creating-manifest/addons.md
   - Custom Responses: creating-manifest/handling-custom-responses.md
   - Visual Settings: creating-manifest/visual-settings.md

- Samples:
   - Overview: samples.md

- Troubleshooting: troubleshooting.md

- CS vs Jelastic Versions: jelastic-cs-correspondence.md

extra:
  versions:
    1.6: 5.5
    1.6.1: 5.5-b3
    1.6.2: 5.6-b2
    1.6.3: 5.6-b4
    1.6.5: 5.6-b9
    1.7: 5.7-b1
    1.7.2: 5.7-b2
    1.7.3: 5.7-b3
    1.7.4: 5.7-b4
    1.7.6: 5.7-b6
    1.7.7: 5.7-b7
    1.7.8: 5.7-b8
    1.8.1: 5.8-b1
    1.8.2: 5.8-b2