site_name: Cloud Scripting
site_url: http://
copyright: Copyright &copy; Jelastic, Inc.

use_absolute_urls: true
include_search: true
theme_center_lead: false


theme_dir: './theme/readthedocs'
repo_url: 'https://github.com/cloudscripting/docs/edit/1.4/docs/'

markdown_extensions:
  - admonition
  - toc
  - tables
  - markdown.extensions.myextension
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

pages:

- GETTING STARTED:
   - Overview: index.md
   - Quick Start: quick-start.md

- Creating Manifest:
   - Basic Configs: creating-manifest/basic-configs.md
   - Specifying Target Container: creating-manifest/selecting-containers.md
   - Actions: creating-manifest/actions.md
   - Events: creating-manifest/events.md
   - Placeholders: creating-manifest/placeholders.md
   - Conditions and Iterations: creating-manifest/conditions-and-iterations.md
   - Custom Scripts: creating-manifest/custom-scripts.md
   - Add-Ons: creating-manifest/addons.md
   - Custom Responses: creating-manifest/handling-custom-responses.md
   - Visual Settings: creating-manifest/visual-settings.md

- Samples:
   - Overview: samples.md

- Troubleshooting: troubleshooting.md

- CS vs Jelastic Versions: jelastic-cs-correspondence.md

versions:
   releases:
      - 0.9
      - 0.99
      - 1.0
      - 1.1
      - 1.2
      - 1.3
      - 1.4
      - 1.5