site_name: Cloud Scripting
site_url: https://docs.cloudscripting.com/
copyright: Copyright &copy; Virtuozzo, Inc.

#use_absolute_urls: true
#:include_search true
#theme_center_lead: false


theme:
  name: null
  custom_dir: 'theme/readthedocs'
repo_url: 'https://github.com/virtuozzo/cloudscripting-docs/edit/master/docs/'

markdown_extensions:
  - admonition
  - tables
  - markdown-tabs
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

nav:

- GETTING STARTED:
   - Overview: index.md
   - Quick Start: quick-start.md

- Creating Manifest:
   - Basic Configs: creating-manifest/basic-configs.md
   - Specifying Target Container: creating-manifest/selecting-containers.md
   - Actions: creating-manifest/actions.md
   - Events: creating-manifest/events.md
   - Placeholders: creating-manifest/placeholders.md
   - Conditions and Iterations: creating-manifest/conditions-and-iterations.md
   - Custom Scripts: creating-manifest/custom-scripts.md
   - Mixins: creating-manifest/mixins.md
   - Add-Ons: creating-manifest/addons.md
   - Custom Responses: creating-manifest/handling-custom-responses.md
   - Visual Settings: creating-manifest/visual-settings.md

- Samples:
   - Overview: samples.md

- Troubleshooting: troubleshooting.md

- CS vs Virtuozzo PaaS Versions: virtuozzo-cs-correspondence.md

extra:
  versions:
    6.3.2: 6.3-2
    7.0.2: 7.0-2
    7.2.1: 7.2-1
    7.3.1: 7.3-1
    8.0.2: 8.0-2
    8.1.1: 8.1-1
    8.2.2: 8.2-2
    8.2.4: 8.2-4
    8.2.5: 8.2-5
    8.3.1: 8.3-1
    8.3.2: 8.3-2
    8.3.3: 8.3-3
    8.4.1: 8.4-1
    8.6.1: 8.6.1
    8.6.2: 8.6.2
    8.8.1: 8.8.1
    8.10.1: 8.10.1
